blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Help and Support
    url: https://github.com/postalhq/postal/discussions/new?category=Help-and-Support
    about: Get friendly support from the community on Github Discussions.

  - name: ğŸ¦Š Feature Suggestions
    url: https://github.com/postalhq/postal/discussions/new?category=Feature-Suggestions
    about: Suggest a new feature that should be added to Postal.