blank_issues_enabled: false
contact_links:
  - name: ğŸ’» Installation help
    url: https://github.com/postalhq/postal/discussions/new?category=Installation-help
    about: If you have questions about running Postal on your servers, use GitHub Discussions.

  - name: ğŸ™ Help with using Postal
    url: https://github.com/postalserver/postal/discussions/new?category=Help-with-using-Postal
    about: If you need help using Postal's features, use GitHub Discussions.

  - name: ğŸ¦Š Feature Suggestions
    url: https://github.com/postalhq/postal/discussions/new?category=Feature-Suggestions
    about: Suggest a new feature that should be added to Postal.
